export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                <nav>
                    <h1>Barra de Navegación</h1>
                    <ul>
                        <li>Home</li>
                        <li>About</li>
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    )
}